### ISSUE TITLE
Segfault when running default SecureML example

### ISSUE THREAD

**Issue by ibarrond** [snwagh/falcon-public#1]
_ENV_: Ubuntu 18.04 with all requirements installed (`g++  make  libssl-dev`).

### Description

After setting up the environment (`make -j`), I tried running the default example (running `make example` with `SecureML` with `MNIST` and `Semi-honest` in the main.cpp), getting a segmentation fault error. I also tried `make command` with the proper config variables in the makefile, with the same result.

### Code to reproduce

```bash
make terminal
#./BMRPassive.out 2 files/IP_localhost  files/keyC files/keyAC files/keyBC >/dev/null &
#./BMRPassive.out 1 files/IP_localhost  files/keyB files/keyBC files/keyAB >/dev/null &
#./BMRPassive.out 0 files/IP_localhost  files/keyA files/keyAB files/keyAC 
#Loading data done.....
#Binding: Address already in use
#makefile:36: recipe for target 'terminal' failed
#make: *** [terminal] Segmentation fault (core dumped)
```

### Additional info
To obtain more info, I ran `make valg`, and I saved the resulting log hoping it will be of help.
[output.log](https://github.com/snwagh/falcon-public/files/5283070/output.log)

**Comment by snwagh** [comment]
I believe it is because Party 2, 1 are running in the background (the `&`at the end of the command) and the ports are fixed. Can you try running pkill BMRPassive.out and then rerun `make terminal`?

**Comment by ibarrond** [comment]
Still the same result. I also tried running each party in a different terminal, to no avail.

**Comment by snwagh** [comment]
Not sure the Segfault is related to the error you print above. The Binding is definitely a sockets issue. 
Check if you have any process named BMRPassive.out running. If it is, kill it first. If there is no such process, then check if some other application is using the same ports as the Falcon code (around 32000 + small numbers). If there is a conflicting process, then you might want to change line 104, 105 from `src/connect.cpp` and then retry. Finally, if all negative, try `make clean; make -j terminal`.

**Comment by ibarrond** [comment]
Still getting segfault 👎 
I checked for running process (`ps -A | grep BMR`). No process running.
I checked for open ports (`sudo netstat -tuapn`). The closest thing is a daemon in 37xxx, but nothing in 32k range.
I tried `make clean; make -j terminal`. I got the same segfault.

**Comment by snwagh** [comment]
I must be missing something, do the 3 parties establish connection? There should be no `#Binding: Address already in use` comment in that case. Maybe add a cost on line 50 ([here](https://github.com/snwagh/falcon-public/blob/master/src/main.cpp#L50)) and `return;` after it. See if that goes through without error. I would debug the binding issue first and then look at the Segfault. 

Anyway, it is hard to diagnose the issue without interactive access to your running set-up. The root cause of the issue could be pretty much anything.

**Comment by ibarrond** [comment]
Looks like the binding issue is gone, but the segfault is still happening.

I narrowed it down to the `synchronize(200000)` ([line 50](https://github.com/snwagh/falcon-public/blob/master/src/main.cpp#L50) of `main.cpp`). I played with the `length` argument in the `synchronize` function, to no avail. I tried changing the default ports (to 321xx), without success.

This is the section of the valgrind output that gets repeated multiple times:

```bash
==30753== Use of uninitialised value of size 8
==30753==    at 0x53D053: _int_malloc (in /make/rast/Banners/falcon-public/BMRPassive.out)
==30753==    by 0x5423D8: calloc (in /make/rast/Banners/falcon-public/BMRPassive.out)
==30753==    by 0x58E4C6: _dl_allocate_tls (in /make/rast/Banners/falcon-public/BMRPassive.out)
==30753==    by 0x509E57: allocate_stack (allocatestack.c:627)
==30753==    by 0x509E57: pthread_create (pthread_create.c:644)
==30753==    by 0x492BF4: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (in /make/rast/Banners/falcon-public/BMRPassive.out)
==30753==    by 0x41D92D: std::thread::thread<void (&)(int, char*, int, int), int&, char*&, int&, int&, void>(void (&)(int, char*, int, int), int&, char*&, int&, int&) (thread:131)
==30753==    by 0x41C933: synchronize(int) (connect.cpp:140)
==30753==    by 0x44A4F4: main (main.cpp:50)
==30753==  Uninitialised value was created by a stack allocation
==30753==    at 0x5C7B73: _dl_init_paths (in /make/rast/Banners/falcon-public/BMRPassive.out)
```

There seems to be some uninitialized memory being used, but I cannot figure out where it comes from without extensive unittesting. Any tips?

**Comment by gmuraru** [comment]
Hmm...maybe an idea would be to check the return code for functions like ```thread``` or ```join``?
from ```initializeCommunication```

**Comment by snwagh** [comment]
@ibarrond Just try simple log debugging, adding `std::cout << "Line no" << std::end;` all over the function trace. I can't think of better ways to debug the issue. @gmuraru suggestion also looks promising.

**Comment by gmuraru** [comment]
@ibarrond could you checkout if [this PR](https://github.com/snwagh/falcon-public/pull/3) solves your issue. I found out that having optimizations activated with the ```fpermissive``` flag might do some "bad" things in the code, which might give errors.

**Comment by snwagh** [comment]
@ibarrond Did you have any luck with fixing your bug?

**Comment by ibarrond** [comment]
Not yet! this week I'm busy finishing a paper. I'll jump straight in next week.

**Comment by ibarrond** [comment]
Well, it sure took me a while, but I have good news on this issue: I pulled the latest version of the repo, then I built the entire project again, and it seems to be working properly! `make terminal` prints the correct output, and there is no segfault to be seen.

I played with some extra examples and it worked flawlessly. Whatever it was, it is not reproducible anymore. 

Closing the issue!

**Comment by imtiyazuddin** [comment]
I was not having any segmentation issues with the default code etc but when I tried to write my own code (by just copy paste from main.cpp) its giving me the same segmentation fault you mentioned above, any other way to find and fix this ??

**Comment by ibarrond** [comment]
@imtiyazuddin coding in C++ can be tricky! make sure you use a nice environment with a proper debugger to inspect these errors, otherwise it might take you a while to pinpoint the root cause.

**Comment by imtiyazuddin** [comment]
upon closer 'inspection' i figured i was missing a parameter :P , my bad. Thanks :)
